### ISSUE TITLE
Reset the scores to zero when someone wins

### ISSUE THREAD

**Issue by mcheatham** [mcheatham/pong-clone#5]

**Comment by JaimeVRodriguez** [comment]
I am looking to make my first contribution and I would like to assist with this issue. Are there any contribution guidelines?

**Comment by mcheatham** [comment]
Great Jaime, I'll assign this one to you. Since most folks who are interested in this project are very new to collaborative software development, we're easing into things. I'll introduce some contribution guidelines in the near future, but for now, just try to write neat-ish code and comment anything weird :)

**Comment by JaimeVRodriguez** [comment]
Sounds good! I appreciate you being flexible and allowing me to learn the process!

**Comment by mcheatham** [comment]
Done!
